Repository itsmedeepak/Hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#10 Added clickable links and removed external links
  README.md
Labels: hacktoberfest, good-first-contribution, good-first-issue, hacktoberfest-accepted

#15 added hacktoberfest image in readme.md and contributing.md
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest, good-first-contribution, hacktoberfest-accepted

#18 Create Alarm_clock app
  Alarm_clock app
Labels: hacktoberfest, hacktoberfest-accepted

#23 Project 44 plagiarism checker python
  Project 44 Plagiarism-checker-Python/README.md
  Project 44 Plagiarism-checker-Python/app.py
  Project 44 Plagiarism-checker-Python/fatma.txt
  Project 44 Plagiarism-checker-Python/image.png
  Project 44 Plagiarism-checker-Python/john.txt
  Project 44 Plagiarism-checker-Python/juma.txt
  Project 44 Plagiarism-checker-Python/pictures/become_a_patron_button.png
  Project 44 Plagiarism-checker-Python/requirements.txt
Labels: hacktoberfest, hacktoberfest-accepted

#36 Create BMI_Calculator.py
  Project-41-BMI Calculator/BMI_Calculator.py
Labels: hacktoberfest-accepted

#41 Added OTP generator using python
  Project 40 otp_generator/generateOTP.py
  Project 40 otp_generator/readme.md
Labels: hacktoberfest, hacktoberfest-accepted, progress

#24 project-45-wattpad book downloader using tkinter
  Project-45-wattpad downloader/README.md
  Project-45-wattpad downloader/wattpadApp.py
Labels: progress

#81 ComputerQuizGame added
  ComputerQuizGame/Game.py
Labels: hacktoberfest-accepted

#89 Update in project 45
  Project-45-Jarvis-AI/README.md
Labels: hacktoberfest-accepted

#101 Update README.md
  Slack-Bot/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#107 Update main.py
  Project-12-guess-the-number/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#108 Update readme.md
  Project-48-Egg Catcher/readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#109 Add files via upload
  whether-main/whether.py
Labels: hacktoberfest, hacktoberfest-accepted

#110 Update README.md
  Python-Planet-Simulation/README.md
Labels: hacktoberfest, good-first-issue, hacktoberfest-accepted

#111 Update main.py
  Project-08-password-encrypter-decrypter/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#112 created BMI_Calculator.md
  Project-05-password-generator/Password Generator.md
  Project-41-BMI Calculator/BMI_Calculator.md
Labels: hacktoberfest, hacktoberfest-accepted

#115 Created Password Encryptor Decryptor.md
  Project-08-password-encrypter-decrypter/Password Encryptor Decryptor.md
Labels: hacktoberfest

#135 Create PasswordChecker.py
  Project 59 - Password Checker/PasswordChecker.py
Labels: hacktoberfest, hacktoberfest-accepted

#133 Hactoberfest
  Algorithms/Pattern Fast Slow Pointer/linkedListCycle.py
  Algorithms/Sliding Window/LongestSubstringWithKDistinctCharacters.py
  Algorithms/Sliding Window/LongestSubstring_with_K_DistinctCharacters.py
  Algorithms/Sliding Window/averageContiguousSubarrays.py
  Algorithms/Sliding Window/smallestSubarrayWithGivenSum.py
  Algorithms/Two Pointers/pair_with_target_sum.py
  Algorithms/Two Pointers/removeDuplicates.py
  Algorithms/Two Pointers/squaring_A_sorted_Array.py
  Algorithms/bubblesort.py
  Algorithms/heapsort.py
  Algorithms/kadane algorithm.py
  Algorithms/merger_sort.py
  Algorithms/quick_sort.py
  Data Structures/Linked List/circularDoublyLL.py
  Data Structures/Linked List/circularSinglyLL.py
  Data Structures/Linked List/doublyLL.py
  Data Structures/Linked List/singlyLL.py
  Data Structures/Queue/Queue.py
  Data Structures/Stack/Node.py
  Data Structures/Stack/Stack.py
  Data Structures/Stack/__pycache__/Node.cpython-39.pyc
  Data Structures/Stack/usingList.py
  Data Structures/Tree/treeStructure.py
Labels: hacktoberfest, hacktoberfest-accepted

#131 Update caculator.py
  project-58-calculator/caculator.py
Labels: hacktoberfest, hacktoberfest-accepted

#137 Create PasswordChecker.md
  Project 59 - Password Checker/PasswordChecker.md
Labels: hacktoberfest, hacktoberfest-accepted

#152 Add files via upload
  matrix/8.py
Labels: hacktoberfest, hacktoberfest-accepted

#156 Added a sudoku solver python program
  SudokuSolver/__init__.py
  SudokuSolver/main.py
  SudokuSolver/readme.md
  SudokuSolver/solver.py
Labels: hacktoberfest, hacktoberfest-accepted

#161 Project-60-Typing_speed_game
  Project-60-Typing_speed_game/README.md
  Project-60-Typing_speed_game/speed.py
  Project-60-Typing_speed_game/type_speed_img.png
Labels: hacktoberfest, hacktoberfest-accepted

#171 added tertis game
  Project-40-'Tetris-Game/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#173 Update main.py
  Project-48-8 Bit_Game_using_Pygame/main.py
Labels: hacktoberfest, hacktoberfest-accepted
